sudo: required

language: docker

services:
  - docker

install:
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install -y --no-install-recommends qemu-user-static binfmt-support
  - sudo update-binfmts --display qemu-arm

script:
  - docker build -t skastenholz/rpi-homegear:stable rpi-stable/

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker tag skastenholz/rpi-homegear:stable skastenholz/rpi-homegear:latest;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push skastenholz/rpi-homegear:stable;
    docker push skastenholz/rpi-homegear:latest;
    fi
